
spring:
    security:
        user:
            name: "user"
            password: 1234
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://svc.sel4.cloudtype.app:31264/ddoiddoi
        username: root
        password: 1234
    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: update
            use-new-id-generator-mappings: false
        show-sql: true
        properties:
            hibernate:
                format_sql: true